### ISSUE TITLE
Validando inputs não numéricos

### ISSUE THREAD

**Issue by lndaquino** [dilowagner/singo-ie-validation#1]
Eu estou testando o pacote para um projeto e verifiquei que ele dá erro em inputs que não contenham nenhum número. Criei uma feature e testes para retornar como invalidas as IEs que não contenham nenhum número. Por exemplo, uma IE inválida seria "blablabla". Caso tenha interesse pode liberar meu usuário para fazer push nesse reposítório em uma nova branch para análise e posterior merge com a branch principal.

**Comment by dilowagner** [comment]
Opaa, @lndaquino  

show man...
Claro, pode mandar ae...

Mas por padrão vc já consegue abrir um pull-request, não?
Cria um fork desse projeto pra vc, cria a branch a partir do master
Depois só commitar/push ae vc consegue abrir o pull-request aqui pra mim...

Tá dando algum erro nesse processo?
E obrigado pela contribuição!

**Comment by lndaquino** [comment]
Fiz o fork e pull request. Antes tinha feito um pull direto do seu repositório e na ora do push de uma nova brach ele deu forbiden

 

De: Diego Wagner <notifications@github.com> 
Enviada em: quinta-feira, 4 de março de 2021 13:09
Para: dilowagner/singo-ie-validation <singo-ie-validation@noreply.github.com>
Cc: lndaquino <lucas.aquino@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [dilowagner/singo-ie-validation] Validando inputs não numéricos (#1)

 

Opaa, @lndaquino <https://github.com/lndaquino> 

show man...
Claro, pode mandar ae...

Mas por padrão vc já consegue abrir um pull-request, não?
Cria um fork desse projeto pra vc, cria a branch a partir do master
Depois só commitar/push ae vc consegue abrir o pull-request aqui pra mim...

Tá dando algum erro nesse processo?
E obrigado pela contribuição!
