### ISSUE TITLE
Erro encontrado com o estado de SP

### ISSUE THREAD

**Issue by ranchocrudes** [dilowagner/singo-ie-validation#5]
Fazendo testes de validação com varios CNPJs, acabei encontrando a IE 330.062.780.110, ela a principio esta correta, fiz a verifcação em outras plataformas e outras bibliotecas e passou, em sp.go na linha 54 adicionei a divisão por 10 e passou todos as IE que tinha.

Doing validation tests with several CNPJs, I ended up finding IE 330.062.780.110, it is correct in principle, I checked it on other platforms and other libraries and it passed, in sp.go on line 54 I added the division by 10 and it passed all IE it had

secondDigit := strconv.Itoa(mod % 10)

**Comment by dilowagner** [comment]
Legal @ranchocrudes 
Vou verificar para adicionar um fix pra isso

**Comment by dilowagner** [comment]
Feito! Valeu @ranchocrudes 👍🏻
