### ISSUE TITLE
Atualização no estado de GO

### ISSUE THREAD

**Issue by ranchocrudes** [dilowagner/singo-ie-validation#7]
Foi atualizado os iniciais do estado de GO, e apartir da data 13/01/2023 começou a valer, as iniciais que começam com 10,11,15 ou 20 a 29. Com isso resolvi fazendo alterações na Função IsStartWith.
A chamada com a atualização ficou assim !rule.IsStartWith(insc, "20", 29)

The initials of the GO state were updated and, as of 01/13/2023, the initials starting with 10, 11, 15 or 20 to 29 became effective. With that, I decided to make changes to the IsStartWith function.
The call with the update looked like this !rule.IsStartWith(insc, "20", 29)

IE: 200193023

```
func (r *Rules) IsStartWith(insc string, value string, end ...int) bool {
	var i, _ = strconv.Atoi(value)
	
	if len(end) == 0 {
		return insc[:len(value)] == value
	}
	for i < end[0] {
		if insc[:len(i)] == value {
			return true
		}
          i++
	}

	return false
}
```

**Comment by dilowagner** [comment]
Valeeeu mais uma vez @ranchocrudes - obrigado pela contribuicao!
Feito, eu só mudei um pouco a implementacao e apliquei alguns testes.

Na verdade eu criei outra funcao separada mesmo, que talvez possamos usar em outros casos também.
Ao invés de passar uma string e um integer, devemos passar duas string de inicio e fim. 

Sinceramente, isso ainda ficou um pouco estranho na minha cabeca (mas resolve hehe)
